[tool.ruff]
line-length = 119

[tool.ruff.lint]
select = ["E", "W", "F", "I", "UP"]
ignore = ["E501"] # Ignore "line too long", the formatter handles it

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"manage.py" = ["E402"]